---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install webserver on ubuntu ansible node
    apt:
      name: "{{myubunutwebpack}}"
      state: present
    when: ansible_os_family =="Debian"

  - name:  i want to start webserver on ubuntu
    service:
      name: "{{myubunutwebpack}}"
      state: started
    when: ansible_os_family =="Debian"

  - name: i want to install webserver on RedHat ansible nodes
    yum: 
      name: "{{myredhatwebpack}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name: i want start webserver on RedHat
    service:
       name: "{{myredhatwebpack}}"
       state: started
    when: ansible_os_family =="RedHat"