---
- name: i want copy tomcat user file into node side
  template:
     src: templates/mytomuser.j2
     dest: /opt/tomcat/conf/tomcat-users.xml

- name: i want to copy manager context file into node side
  template:
    src:  templates/managercontext.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: i want to copy host manager context file into node side
  template:
    src:  templates/hostmanagercontext.j2
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml