---
# tasks file for mywebrole
- name: i want to install webserver on ubuntu node
  apt: 
    name: apache2
    state: present
    
- name: copy indexfile into node side
  template:
     src: templates/myindex.j2
     dest: /var/www/html/index.html
   